# GET http://localhost:8082/getListAcc/61e927660552504308d5b7d5/Bank
# Content-Type: application/json

# {
#     "linkType": "acb"
# }

# POST http://localhost:8082/linkAcc/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWYxMDk4MTJmZjI4MDI5MDZkOTg4OGIiLCJpYXQiOjE2NDgwMjQ3NjksImV4cCI6MTY1ODgyNDc2OX0.7-l5xxGgyhH47HeNtuuMB_ehhMAVV2KMqO9bibPiUoU
# Content-Type: application/json

# {
#     "accNum" : "123123123456",
#     "partiesName": "7895",
#     "token": "ABC",
#     "linkType": "Bank"
# }

# POST http://localhost:8082/transaction/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWYxMDk4MTJmZjI4MDI5MDZkOTg4OGIiLCJpYXQiOjE2NDgwMjQ3NjksImV4cCI6MTY1ODgyNDc2OX0.7-l5xxGgyhH47HeNtuuMB_ehhMAVV2KMqO9bibPiUoU
# Content-Type: application/json

# {
#     "type" : "transfer",
#     "name": "Lien",
#     "phone": "0939807295",
#     "money": "400"
# }

# POST http://localhost:8082/test/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWYxMDk4MTJmZjI4MDI5MDZkOTg4OGIiLCJpYXQiOjE2NDgwMDEzNjUsImV4cCI6MTY1ODgwMTM2NX0.WGuLofPyPX3T6l2J_jVmT2vVi5GEWCuzJcDPRA8BuIo
# Content-Type: application/json

# {
#     "type" : "transfer",
#     "name": "Lien",
#     "phone": "0939807295",
#     "money": "360"
# }

# POST http://localhost:8082/register
# Content-Type: application/json

# {
#     "password" : "transfer",
#     "name": "Lien",
#     "phone": "0939807295",
#     "dob": "31/05/2000",
#     "email": "lulien32@gmail.com"
# }


# GET http://localhost:8082/getHistory/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWYxMDk4MTJmZjI4MDI5MDZkOTg4OGIiLCJpYXQiOjE2NDMxODk3MDh9.rC07Ccxxakc7pc6YK_ij5tSYDa9aH_HwtzI-cP6szFs


# POST http://localhost:8082/signin
# Content-Type: application/json

# {
#     "password" : "transfer",
#     "phone": "0939807294"
# }

# POST  https://onlpay-test.herokuapp.com/welcome

